apiVersion: v1
kind: Secret
metadata:
  name: cd2023bfs1g3-dev-db-secret
  annotations:
    "helm.sh/resource-policy": "keep"  
data:
  password: {{  "cd2023bfs1g3"  | b64enc }}
  user: {{ "postgres" | b64enc }}
  postgresql-password: {{  "cd2023bfs1g3"  | b64enc }}

